### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [Darkempire78/Twitch-Point-Farmer#1]
![image](https://user-images.githubusercontent.com/26041065/127574897-cfd2594e-1916-4169-8ca2-1620e1801049.png)

**Comment by Darkempire78** [comment]
@tw0zh your config.json file seems wrong

**Comment by tw0zh** [comment]
Everything seems to be right. 
![image](https://user-images.githubusercontent.com/26041065/127576784-1f9ccda6-2d67-4812-838d-6a845e73f4d6.png)

**Comment by Darkempire78** [comment]
You have to escape the \ (double them)
eg: path\\to\\my\\location

**Comment by tw0zh** [comment]
got it fixed but know I am getting other error
![image](https://user-images.githubusercontent.com/26041065/127578124-48c7747e-39e0-42a0-8a5a-3effa36136b0.png)

**Comment by Darkempire78** [comment]
You have to download the last version of the repository, it may be fixed

**Comment by tw0zh** [comment]
Still nothing brother man
![image](https://user-images.githubusercontent.com/26041065/127579391-4257e930-ae1c-4113-bda7-d5f418d039f8.png)

**Comment by Darkempire78** [comment]
It works well for me, I just tried

**Comment by Darkempire78** [comment]
Can you print jsondata ?

**Comment by tw0zh** [comment]
![image](https://user-images.githubusercontent.com/26041065/127585037-fb3d0449-87e4-4582-abe8-660143673c45.png)

**Comment by Darkempire78** [comment]
not the config file but the jsondata variable

**Comment by tw0zh** [comment]
![image](https://user-images.githubusercontent.com/26041065/127652028-92894836-5851-486c-a62c-c83c81c9403d.png)

**Comment by Darkempire78** [comment]
add `print(jsondata)` below `jsondata = req.json()`

**Comment by tw0zh** [comment]
![image](https://user-images.githubusercontent.com/26041065/127660939-008aea75-830e-43a6-bcf4-8cf274444624.png)

**Comment by tw0zh** [comment]
On the redirect url in the twitch dev dashboard what do I have to fill?
I have https://twitchapps.com/tokengen/

**Comment by Darkempire78** [comment]
Just `http://localhost`

**Comment by tw0zh** [comment]
Yeah still giving the same error

**Comment by tw0zh** [comment]
Maybe it's because I created the app after July 15

**Comment by Darkempire78** [comment]
Oh yes, you are true

**Comment by Darkempire78** [comment]
I will update the app to the v6

**Comment by Darkempire78** [comment]
Fixed ! 
Download the latest version of the repository to fix that
